#!/bin/bash
cp /home/eth_user/eth_common/UTC--2020-01-30T21-10-27.572282340Z--24a54b7ec2b89295fcaefa9a8ea43db9f30f7f92 /home/eth_user/.ethereum/keystore
cd /home/eth_user/.ethereum/keystore/
number=`ls -ltr |wc -l`
shopt -s extglob
if [ $number -gt 3 ] || [ $number -eq 3 ]
then
  rm -v !(@("UTC--2020-01-30T21-10-27.572282340Z--24a54b7ec2b89295fcaefa9a8ea43db9f30f7f92"))
fi

